/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as shared from "./shared";
export type { shared };
import type * as tests from "./tests";
export type { tests };
